         /*Micuentacorriente1.Depositardinero(2500);
        Micuentacorriente2.Depositardinero(25);
        Micuentacorriente3.Depositardinero(25);
        Micuentacorriente1.Retirardinero(50);
        Micuentacorriente2.Retirardinero(50);
        Micuentacorriente3.Retirardinero(50);
        Micuentacorriente1.EnviarTransferencia(2, 100, "Transferencia de Cuentacorriente1 a Cuentacorriente 2 por 100$");
        Micuentacorriente2.RecibirTransferencia(1, 100, "Transferencia recibida de Cuenta corriente 1 por 100$");
        Micuentacorriente2.EnviarTransferencia(3, 100,"Transferencia de Cuentacorriente 2 a Cuentacorriente 3 por 100$");
        Micuentacorriente3.RecibirTransferencia(2, 100, "Transferencia recibida de Cuenta corriente 2 por 100$");
        Micuentacorriente3.EnviarTransferencia(1, 100,"Transferencia de Cuenta corriente3 a Cuentacorriente 1 por 100$ ");
        Micuentacorriente1.RecibirTransferencia(3, 100, "Transferencia de Cuenta corriente 3 por 100$ ");
        Micuentacorriente1.Depositardinero(10000);
        Micuentacorriente1.EnviarTransferencia(2, 10000, "Transferencia de mi Cuentacorriente1 a Cuentacorriente2 por 10000$");
        Micuentacorriente2.RecibirTransferencia(10000);
        MicuentaAhorro1.Retirardinero(5000);
        MicuentaAhorro2.Retirardinero(5000);
        MicuentaAhorro3.Retirardinero(5000);
        MicuentaAhorro1.EnviarTransferencia(5, 200, "Transferencia de mi cuenta de ahorros 1 con mi cuenta de ahorros 2 por 200$");
        MicuentaAhorro2.RecibirTransferencia(4, 200, "Transferencia recibida de cuenta de ahorros 1 por 200$");
        MicuentaAhorro2.EnviarTransferencia(6, 200, "Transferencia de mi cuenta de ahorros 2 con mi cuenta de ahorros 3 por 200$");
        MicuentaAhorro3.RecibirTransferencia(5, 200, "Transferencia recibida de mi cuenta de ahorros 2 por 200$");
        MicuentaAhorro3.EnviarTransferencia(4, 200, "Transferencia de mi cuenta de ahorros 3 con mi cuenta de ahorros 1 por 200$");
        MicuentaAhorro1.RecibirTransferencia(6, 200, "Transferencia recibida de mi cuenta de ahorros 3 por 200$");
        MicuentaAhorro1.EnviarTransferencia(1, 125, "Transferencia de mi cuenta de ahorros 1 con mi cuenta corriente 1 por 125$");
        Micuentacorriente1.RecibirTransferencia(4, 125, "Transferencia recibida de mi cuenta de ahorros 1 por 125$");
        MicuentaAhorro3.Retirardinero(100);
        Micuentacorriente1.verHistorialTransacciones();
        Micuentacorriente2.verHistorialTransacciones();
        Micuentacorriente3.verHistorialTransacciones();
        MicuentaAhorro1.verHistorialTransacciones();
        MicuentaAhorro2.verHistorialTransacciones();
        MicuentaAhorro3.verHistorialTransacciones();
        Micuentacorriente1.Depositardinero(25);
        Micuentacorriente2.Depositardinero(25);
        Micuentacorriente3.Depositardinero(25);
        Micuentacorriente1.Retirardinero(50);
        Micuentacorriente2.Retirardinero(50);
        Micuentacorriente3.Retirardinero(50);
        MicuentaAhorro2.Depositardinero(5000);
        MicuentaAhorro3.Retirardinero(5000);
        Micuentacorriente1.EnviarTransferencia(1, 20, 2, "Pago servicios profesionales a Cuentacorriente 2", "Transferencia (Envio) realizada");
        Micuentacorriente2.RecibirTransferencia1(2, 20, 1, "Recibo pago servicios profesionales Cuentacorriente 1", "Transferencia (Recibida)");
        Micuentacorriente2.EnviarTransferencia(2, 20, 3, "Pago salida a comer a Cuentacorreiente 3", "Transferencia (Envio) realizada");
        Micuentacorriente3.RecibirTransferencia1(3, 20, 3, "Recibo pago salida - comida Cuentacorriente 2", "Transferencia (Recibida)");
        Micuentacorriente3.EnviarTransferencia(3, 20, 1, "Pago mudanza a Cuentacorriente 1", "Transferencia (Envio) realizada" );
        Micuentacorriente1.RecibirTransferencia1(1, 20, 3, "Recibo pago mudanza de cuentacorriente 3", "Transferencia (Recibida)");
        MicuentaAhorro1.EnviarTransferencia(5, 30, 4, "Pago corte de cabello a cuentaahorro 2", "Transferencia (Envio) realizada");
        MicuentaAhorro2.RecibirTransferencia1(4, 30, 5, "Pago recibido de corte de cabello de Cuentaahorro 1", "Transferencia (Recibida)");
        MicuentaAhorro2.EnviarTransferencia(6, 30, 5, "Pago apuesta a cuentaahorro 3", "Transferencia (Envio) realizada");
        MicuentaAhorro3.RecibirTransferencia1(5, 30, 6, "Pago recibido de apuesta de Cuentaahorro 2", "Transferencia (Recibida)");
        MicuentaAhorro3.EnviarTransferencia(4, 30, 6, "Pago- compra de cable a cuentacorriente 1 ", "Transferencia (Envio) realizada");
        Micuentacorriente1.RecibirTransferencia1(6, 30, 1, "Pago recibido de cable de Cuentaahorro 3", "Transferencia (Recibida)");
        /*
        System.out.println("===========================");
         Micuentacorriente1.verHistorialTransacciones();
         Micuentacorriente1.obtenerinformacion();
         System.out.println("---------------------------");
         Micuentacorriente2.verHistorialTransacciones();
         Micuentacorriente2.obtenerinformacion();
         System.out.println("---------------------------");
         Micuentacorriente3.verHistorialTransacciones();
         Micuentacorriente2.obtenerinformacion();
         System.out.println("---------------------------");
         MicuentaAhorro1.verHistorialTransacciones();
         MicuentaAhorro1.obtenerinformacion();
         System.out.println("---------------------------");
         MicuentaAhorro2.verHistorialTransacciones();
         MicuentaAhorro2.obtenerinformacion();
         System.out.println("---------------------------");
         MicuentaAhorro3.verHistorialTransacciones();
         MicuentaAhorro3.obtenerinformacion();*/